import type { Metadata } from "next";
import { STIX_Two_Text, Figtree } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const seedFiFont = STIX_Two_Text({
  variable: "--font-stix",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const figTree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SeedFi Website",
  description: "Generated by create next app",
  // fav
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${seedFiFont.variable} ${figTree.variable}`}>
      <body>
        <div className="w-full border-2">
          <Header />
          <main className="w-full min-h-screen">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
